# Contains the configuration for the whole server
# Dont set secrets, passwords, api_keys etc. in this file. Use '.env' file for that

maxProcess = 12 # Max number of cpu process to be used by go runtime 
gwDBRetention = 1
routerDBRetention = 0

[Gateway]
webPort = 8080
maxBatchSize = 32
batchTimeoutInMS = 20
maxDBWriterProcess = 4
CustomVal = "GW"
respMessage = "OK"


[JobsDB]
# Migration related parameters
jobDoneMigrateThres = 0.8
jobStatusMigrateThres = 5
maxDSSize = 100000
maxMigrateOnce = 10
mainCheckSleepDurationInS = 2

[Integrations]
maxChanSize = 2048
numTransformWorker = 16
maxRetry = 3
retrySleepInMS = 100

[Router]
jobQueryBatchSize = 10000
updateStatusBatchSize = 1000
readSleepInMS = 10
noOfWorkers = 16
noOfJobsPerChannel = 1000
ser = 3
maxSleepInS = 3600
maxStatusUpdateWaitInS = 5
randomWorkerAssign = false
useTestSink = false

[Processor]
loopSleepInMS = 10
batchSize = 1000
sessionThresholdEvents = 20
sessionThresholdInS = 20
processSessions = true
