version: '3.7'

services:
  db:
    image: postgres:11-alpine
    env_file:
      - docker.env
    ports:
      - "5433:5432"

  rudder:
    depends_on:
      - db
    build: 
      context: ./
      dockerfile: Dockerfile

    entrypoint: sh -c './wait-for db:5432 -- rudder-server'

    ports:
      - "8081:8080"
    env_file:
      - docker.env
    environment:
      - JOBS_DB_HOST=db
